import { calculateFinancingCost } from './calculationUtils.js';
import { formatINR } from '../utils/formatters.js';

/**
 * Deterministic Decision Engine Module for TermPilot
 * Evaluates financial metrics against transparent rules to output:
 * 1. Financial Pressure Index (0-100)
 * 2. Risk Level (LOW, MODERATE, HIGH)
 * 3. Decision (ACCEPT, NEGOTIATE, HIGH RISK / REVIEW)
 * 4. Scenario Comparison Matrix (Net 15, 30, 45, 60, 90)
 * 5. Data-driven Structured Explanations
 *
 * @param {Object} metrics - Financial metrics generated by financialEngine
 * @returns {Object} decisionResult
 */
export const evaluateFinancialDecision = (metrics) => {
  const {
    dealValue,
    proposedPaymentTermDays,
    availableCash,
    monthlyOperatingExpenses,
    upcomingObligations,
    existingReceivables,
    annualCostOfCapital,
    postObligationCash,
    cashRunwayMonths,
    receivableExposureRatio,
    dealExposureRatio,
    estimatedFinancingCost
  } = metrics;

  // =========================================================================
  // 1. COMPONENT PRESSURE SCORING (0 to 100 scale per factor)
  // =========================================================================

  // A. Liquidity Risk Score (40% Weight)
  // Rule: <=0 cash or <1 mo runway = 100 pts (HIGH); 1 to <2 mo runway = 50 pts (MODERATE); >=2 mo runway = 0 pts (LOW)
  let liquidityScore = 0;
  let liquidityRiskLevel = 'LOW';
  if (postObligationCash <= 0 || cashRunwayMonths < 1) {
    liquidityScore = 100;
    liquidityRiskLevel = 'HIGH';
  } else if (cashRunwayMonths >= 1 && cashRunwayMonths < 2) {
    liquidityScore = 50;
    liquidityRiskLevel = 'MODERATE';
  } else {
    liquidityScore = 0;
    liquidityRiskLevel = 'LOW';
  }

  // B. Deal Exposure Risk Score (25% Weight)
  // Rule: dealValue / availableCash > 200% (2.0x) = 75 pts; 100%-200% = 50 pts; <=100% = 0 pts
  let dealExposureScore = 0;
  let dealExposureLevel = 'LOW';
  if (dealExposureRatio > 200) {
    dealExposureScore = 75;
    dealExposureLevel = 'HIGH';
  } else if (dealExposureRatio > 100) {
    dealExposureScore = 50;
    dealExposureLevel = 'MODERATE';
  } else {
    dealExposureScore = 0;
    dealExposureLevel = 'LOW';
  }

  // C. Receivables Exposure Risk Score (15% Weight)
  // Rule: receivables / cash > 200% = 75 pts; 100%-200% = 50 pts; <=100% = 0 pts
  let receivablesScore = 0;
  let receivablesLevel = 'LOW';
  if (receivableExposureRatio > 200) {
    receivablesScore = 75;
    receivablesLevel = 'HIGH';
  } else if (receivableExposureRatio > 100) {
    receivablesScore = 50;
    receivablesLevel = 'MODERATE';
  } else {
    receivablesScore = 0;
    receivablesLevel = 'LOW';
  }

  // D. Payment Term Pressure Score (20% Weight)
  // Rule: <=30 days = 0 pts (LOW); 31-60 days = 30 pts (MODERATE); >60 days = 100 pts (HIGH)
  let termPressureScore = 0;
  let termPressureLevel = 'LOW';
  if (proposedPaymentTermDays > 60) {
    termPressureScore = 100;
    termPressureLevel = 'HIGH';
  } else if (proposedPaymentTermDays > 30) {
    termPressureScore = 30;
    termPressureLevel = 'MODERATE';
  } else {
    termPressureScore = 0;
    termPressureLevel = 'LOW';
  }

  // =========================================================================
  // 2. WEIGHTED FINANCIAL PRESSURE INDEX & PRELIMINARY DECISION
  // =========================================================================
  // Weighted calculation:
  // Liquidity (40%) + Deal Exposure (25%) + Receivables (15%) + Term Pressure (20%)
  const weightedScore = (liquidityScore * 0.40) +
                        (dealExposureScore * 0.25) +
                        (receivablesScore * 0.15) +
                        (termPressureScore * 0.20);

  const financialPressureScore = Math.min(100, Math.max(0, Math.round(weightedScore)));

  // Risk Classification
  let riskLevel = 'LOW';
  let rawDecision = 'ACCEPT';

  if (financialPressureScore >= 60) {
    riskLevel = 'HIGH';
    rawDecision = 'HIGH RISK / REVIEW';
  } else if (financialPressureScore >= 30) {
    riskLevel = 'MODERATE';
    rawDecision = 'NEGOTIATE';
  } else {
    riskLevel = 'LOW';
    rawDecision = 'ACCEPT';
  }

  // HARD CONSTRAINTS OVERRIDE
  // Hard Rule: If post-obligation cash < 0 or runway < 1 month, decision CANNOT be ACCEPT.
  let decision = rawDecision;
  if ((postObligationCash < 0 || cashRunwayMonths < 1) && decision === 'ACCEPT') {
    decision = 'NEGOTIATE';
  }

  // =========================================================================
  // 3. PAYMENT TERM SCENARIO COMPARISON MATRIX
  // =========================================================================
  const termPresets = [15, 30, 45, 60, 90];
  const scenarios = termPresets.map((termDays) => {
    const cost = calculateFinancingCost(dealValue, annualCostOfCapital, termDays);
    const savingsVsProposed = estimatedFinancingCost - cost;
    const isProposed = termDays === Number(proposedPaymentTermDays);

    return {
      termDays,
      label: `Net ${termDays}`,
      financingCost: cost,
      savingsVsProposed,
      isProposed
    };
  });

  // Calculate recommended term direction
  // Note: Only recommend a shorter term if the decision is NEGOTIATE or HIGH RISK / REVIEW.
  let recommendedTermDays = proposedPaymentTermDays;
  let estimatedSavings = 0;

  if (decision === 'NEGOTIATE' || decision === 'HIGH RISK / REVIEW') {
    if (proposedPaymentTermDays > 30) {
      recommendedTermDays = 30; // Recommend Net 30 as optimal B2B benchmark
    } else if (proposedPaymentTermDays > 15) {
      recommendedTermDays = 15;
    }

    const recommendedScenario = scenarios.find((s) => s.termDays === recommendedTermDays);
    if (recommendedScenario) {
      estimatedSavings = Math.max(0, estimatedFinancingCost - recommendedScenario.financingCost);
    }
  }

  // =========================================================================
  // 4. STRUCTURED DATA-DRIVEN EXPLANATION POINTS
  // =========================================================================
  const postCashFormatted = formatINR(postObligationCash);
  const dealValueFormatted = formatINR(dealValue);
  const estimatedCostFormatted = formatINR(Math.round(estimatedFinancingCost));
  const savingsFormatted = formatINR(Math.round(estimatedSavings));
  const runwayStr = cashRunwayMonths >= 999 ? 'unlimited' : `${cashRunwayMonths.toFixed(1)} month(s)`;
  const dealRatioStr = `${dealExposureRatio.toFixed(1)}% (${(dealExposureRatio / 100).toFixed(2)}×)`;

  const structuredExplanations = {
    liquidity: `Post-obligation cash is ${postCashFormatted}, providing approximately ${runwayStr} of OpEx coverage.`,
    dealExposure: `The ${dealValueFormatted} deal value represents ${dealRatioStr} of available cash reserves.`,
    creditTermCost: `Net ${proposedPaymentTermDays} has an estimated capital carrying cost of ${estimatedCostFormatted}.`,
    alternative: decision === 'ACCEPT'
      ? `Proposed Net ${proposedPaymentTermDays} is within safe working-capital limits.`
      : recommendedTermDays < proposedPaymentTermDays
        ? `Net ${recommendedTermDays} reduces estimated capital carrying cost to ${formatINR(Math.round(calculateFinancingCost(dealValue, annualCostOfCapital, recommendedTermDays)))}, a potential reduction of ${savingsFormatted}.`
        : `Proposed Net ${proposedPaymentTermDays} is already a short credit term; cash-flow risk stems primarily from working capital liquidity reserves.`,
    rationale: decision === 'ACCEPT'
      ? `Because liquid cash reserves comfortably support the proposed credit window, TermPilot approves accepting Net ${proposedPaymentTermDays}.`
      : recommendedTermDays < proposedPaymentTermDays
        ? `Because the shorter term materially reduces capital carrying cost while improving liquidity timing, TermPilot recommends negotiating toward Net ${recommendedTermDays}.`
        : `Because working-capital liquidity is constrained, TermPilot recommends negotiating shorter payment terms or requesting an upfront advance.`
  };

  // Simple bullet array for components
  const explanationBullets = [
    structuredExplanations.liquidity,
    structuredExplanations.dealExposure,
    structuredExplanations.creditTermCost,
    structuredExplanations.alternative,
    structuredExplanations.rationale
  ];

  return {
    financialPressureScore, // Index score 0-100
    riskLevel,
    decision,
    recommendedTermDays,
    estimatedSavings,
    scenarios,
    structuredExplanations,
    explanationBullets,
    scoringBreakdown: {
      liquidityScore,
      liquidityRiskLevel,
      dealExposureScore,
      dealExposureLevel,
      receivablesScore,
      receivablesLevel,
      termPressureScore,
      termPressureLevel
    }
  };
};
