import { calculateFinancingCost } from './calculationUtils';

/**
 * Deterministic Decision Engine Module for TermPilot
 * Evaluates financial metrics against transparent rules to output:
 * 1. Financial Pressure Score (0-100)
 * 2. Risk Level (LOW, MODERATE, HIGH)
 * 3. Decision (ACCEPT, NEGOTIATE, HIGH RISK / REVIEW)
 * 4. Scenario Comparison (Net 15, 30, 45, 60, 90)
 * 5. Data-driven Explainability Bullets
 *
 * @param {Object} metrics - Financial metrics generated by financialEngine
 * @returns {Object} decisionResult
 */
export const evaluateFinancialDecision = (metrics) => {
  const {
    dealValue,
    proposedPaymentTermDays,
    availableCash,
    monthlyOperatingExpenses,
    upcomingObligations,
    existingReceivables,
    annualCostOfCapital,
    postObligationCash,
    cashRunwayMonths,
    receivableExposureRatio,
    dealExposureRatio,
    estimatedFinancingCost
  } = metrics;

  // =========================================================================
  // 1. COMPONENT RISK SCORING (0 to 100 scale per factor)
  // =========================================================================

  // A. Liquidity Risk Score (40% Weight)
  // Rule: <=0 cash or <1 mo runway = 100 pts (HIGH); 1 to <2 mo runway = 50 pts (MODERATE); >=2 mo runway = 0 pts (LOW)
  let liquidityScore = 0;
  let liquidityRiskLevel = 'LOW';
  if (postObligationCash <= 0 || cashRunwayMonths < 1) {
    liquidityScore = 100;
    liquidityRiskLevel = 'HIGH';
  } else if (cashRunwayMonths >= 1 && cashRunwayMonths < 2) {
    liquidityScore = 50;
    liquidityRiskLevel = 'MODERATE';
  } else {
    liquidityScore = 0;
    liquidityRiskLevel = 'LOW';
  }

  // B. Deal Exposure Risk Score (25% Weight)
  // Rule: dealValue / availableCash > 200% (2.0x) = 75-100 pts; 100%-200% = 50 pts; <=100% = 0 pts
  let dealExposureScore = 0;
  let dealExposureLevel = 'LOW';
  if (dealExposureRatio > 200) {
    dealExposureScore = 75; // High exposure warning
    dealExposureLevel = 'HIGH';
  } else if (dealExposureRatio > 100) {
    dealExposureScore = 50; // Moderate exposure warning
    dealExposureLevel = 'MODERATE';
  } else {
    dealExposureScore = 0;
    dealExposureLevel = 'LOW';
  }

  // C. Receivables Exposure Risk Score (15% Weight)
  // Rule: receivables / cash > 200% = 75 pts; 100%-200% = 50 pts; <=100% = 0 pts
  let receivablesScore = 0;
  let receivablesLevel = 'LOW';
  if (receivableExposureRatio > 200) {
    receivablesScore = 75;
    receivablesLevel = 'HIGH';
  } else if (receivableExposureRatio > 100) {
    receivablesScore = 50;
    receivablesLevel = 'MODERATE';
  } else {
    receivablesScore = 0;
    receivablesLevel = 'LOW';
  }

  // D. Payment Term Pressure Score (20% Weight)
  // Rule: <=30 days = 0 pts (LOW); 31-60 days = 30 pts (MODERATE); >60 days = 100 pts (HIGH)
  let termPressureScore = 0;
  let termPressureLevel = 'LOW';
  if (proposedPaymentTermDays > 60) {
    termPressureScore = 100;
    termPressureLevel = 'HIGH';
  } else if (proposedPaymentTermDays > 30) {
    termPressureScore = 30;
    termPressureLevel = 'MODERATE';
  } else {
    termPressureScore = 0;
    termPressureLevel = 'LOW';
  }

  // =========================================================================
  // 2. WEIGHTED PRESSURE SCORE & PRELIMINARY DECISION
  // =========================================================================
  // Weighted calculation:
  // Liquidity (40%) + Deal Exposure (25%) + Receivables (15%) + Term Pressure (20%)
  const weightedScore = (liquidityScore * 0.40) +
                        (dealExposureScore * 0.25) +
                        (receivablesScore * 0.15) +
                        (termPressureScore * 0.20);

  const financialPressureScore = Math.min(100, Math.max(0, Math.round(weightedScore)));

  // Risk Classification
  let riskLevel = 'LOW';
  let rawDecision = 'ACCEPT';

  if (financialPressureScore >= 60) {
    riskLevel = 'HIGH';
    rawDecision = 'HIGH RISK / REVIEW';
  } else if (financialPressureScore >= 30) {
    riskLevel = 'MODERATE';
    rawDecision = 'NEGOTIATE';
  } else {
    riskLevel = 'LOW';
    rawDecision = 'ACCEPT';
  }

  // HARD CONSTRAINTS OVERRIDE
  // Hard Rule: If post-obligation cash < 0 or runway < 1 month, decision CANNOT be ACCEPT.
  let decision = rawDecision;
  if ((postObligationCash < 0 || cashRunwayMonths < 1) && decision === 'ACCEPT') {
    decision = 'NEGOTIATE';
  }

  // =========================================================================
  // 3. PAYMENT TERM SCENARIO COMPARISON MATRIX
  // =========================================================================
  const termPresets = [15, 30, 45, 60, 90];
  const scenarios = termPresets.map((termDays) => {
    const cost = calculateFinancingCost(dealValue, annualCostOfCapital, termDays);
    const savingsVsProposed = estimatedFinancingCost - cost;
    const isProposed = termDays === Number(proposedPaymentTermDays);

    return {
      termDays,
      label: `Net ${termDays}`,
      financingCost: cost,
      savingsVsProposed,
      isProposed
    };
  });

  // Calculate recommended term direction
  let recommendedTermDays = proposedPaymentTermDays;
  let estimatedSavings = 0;

  if (decision === 'NEGOTIATE' || decision === 'HIGH RISK / REVIEW') {
    if (proposedPaymentTermDays > 30) {
      recommendedTermDays = 30; // Recommend Net 30 as optimal B2B benchmark
    } else if (proposedPaymentTermDays > 15) {
      recommendedTermDays = 15;
    }

    const recommendedScenario = scenarios.find((s) => s.termDays === recommendedTermDays);
    if (recommendedScenario) {
      estimatedSavings = Math.max(0, estimatedFinancingCost - recommendedScenario.financingCost);
    }
  }

  // =========================================================================
  // 4. DATA-DRIVEN EXPLAINABILITY BULLETS
  // =========================================================================
  const explanationBullets = [];

  // Liquidity bullet
  if (postObligationCash <= 0) {
    explanationBullets.push(`Post-obligation cash is negative or exhausted (₹${postObligationCash.toLocaleString('en-IN')}).`);
  } else {
    explanationBullets.push(`Post-obligation cash is ₹${postObligationCash.toLocaleString('en-IN')}.`);
  }

  // Runway bullet
  explanationBullets.push(
    `Cash runway provides approximately ${cashRunwayMonths.toFixed(1)} month(s) of operating expenses.`
  );

  // Deal exposure bullet
  const dealRatioStr = dealExposureRatio.toFixed(1);
  const dealTimesStr = (dealExposureRatio / 100).toFixed(2);
  explanationBullets.push(
    `The ₹${dealValue.toLocaleString('en-IN')} deal value represents ${dealRatioStr}% (${dealTimesStr}×) of total available cash.`
  );

  // Term cost bullet
  explanationBullets.push(
    `Proposed Net ${proposedPaymentTermDays} creates an estimated financing cost of ₹${Math.round(estimatedFinancingCost).toLocaleString('en-IN')}.`
  );

  // Receivables bullet if high/moderate
  if (receivableExposureRatio > 100) {
    explanationBullets.push(
      `Existing receivables of ₹${existingReceivables.toLocaleString('en-IN')} represent ${receivableExposureRatio.toFixed(1)}% of available cash.`
    );
  }

  return {
    financialPressureScore,
    riskLevel,
    decision,
    recommendedTermDays,
    estimatedSavings,
    scenarios,
    explanationBullets,
    scoringBreakdown: {
      liquidityScore,
      liquidityRiskLevel,
      dealExposureScore,
      dealExposureLevel,
      receivablesScore,
      receivablesLevel,
      termPressureScore,
      termPressureLevel
    }
  };
};
